### ISSUE TITLE
Autenticação no sistema - autocadastro (paciente e nutricionista)

### ISSUE THREAD

**Issue by lilialnas** [i4n-v/NutriBook#18]
- [x] Definir front-end da página autenticação 
- [x] Definir mecanismo de autenticação para os usuários #19 e #31 
- [x] Definir o autocadastro para os dois perfis do usuário #20 #21
- [x] Direcionar o usuário logado para "home do usuário logado #22

**Comment by lilialnas** [comment]
Nesta sprint será feito apenas para uma entidade.
